apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/maven/base?ref=main

resources:
  - 01-workspace-pvc.yaml
  - 02-pipeline.yaml
