---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: mark-pipeline-trigger-template
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: mark-pipeline
        generateName: mark-piplinerun-trigger-
      spec:
        params:
          - name: APP_NAME
            value: "mark-demo"
          - name: APP_GIT_URL
            value: $(tt.params.git-repo-url)
          - name: APP_GIT_REVISION
            value: $(tt.params.git-revision)
        pipelineRef:
          name: mark-demo-pipeline
        workspaces:
        - name: app-source
          persistentVolumeClaim:
            claimName: app-source-pvc
        - name: maven-settings
          configMap:
            name: maven-settings
---
# Trigger binding identifies which fields are to be extracted from
# the webhook JSON payload to be presented to the trigger template
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: mark-pipeline-trigger-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.after)
---
# Event listener is a resource for connecting the trigger binding
# to the trigger template.  It also creates an application running in
# the project namespace that will invoke the pipeline when required
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mark-pipeline-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: GitHub-listener
      bindings:
        - ref: mark-pipeline-trigger-binding
      template:
        ref: mark-pipeline-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: mark-pipeline-event-listener
  name: mark-pipeline-trigger-route
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-mark-pipeline-event-listener
    weight: 100
