apiVersion: apps/v1
kind: Deployment
metadata:
  name: mark-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mark-demo
  template:
    metadata:
      labels:
        app: mark-demo
    spec:
      containers:
      - name: mark-demo
        image: mark-demo:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: '1'
          requests:
            memory: 512Mi
            cpu: 250m        
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: spring.profiles.active
        - name: GREETER_PREFIX
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: greeter.prefix
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
