apiVersion: apps/v1
kind: Deployment
metadata:
  name: mark-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mark-demo
  template:
    metadata:
      labels:
        app: mark-demo
    spec:
      containers:
      - name: mark-demo
        image: mark-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: spring.profiles.active
        - name: GREETER_PREFIX
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: greeter.prefix
