apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nexus
  name: nexus-secret
stringData:
  # MAVEN_SERVER_USERNAME: admin
  # MAVEN_SERVER_PASSWORD: admin123
  # MAVEN_SERVER_HOST: http://nexus.mark-cicd-tools.svc.cluster.local:8081
  # Access the sonar deployed in the mark-cicd-tools project internally
  # http://<app-name>.<project-name>.svc.cluster.local:<port>
  SONAR_SERVER_HOST: http://sonarqube.mark-cicd-tools.svc.cluster.local:9000
