apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mark-config-map-prod

bases:
- ../../base

images:
  - name: mark-demo
    newName: image-registry.openshift-image-registry.svc:5000/mark-pipeline-demo/mark-demo
    newTag: prod

patchesStrategicMerge:
  - app-properties-configmap.yaml
